query($id: ID!){
  product(id: $id){
    id
    sku
    name
    price
    sale_price
    quantity
    weight
    featured
    status
    description
    Images{
      id
      image
    }
    Categories{
      id
      name
      slug
    }
    Brand{
      id
      name
      slug
      logo
    }
  }
}
